### ISSUE TITLE
could you upload the AD

### ISSUE THREAD

**Issue by wuxian0** [ippousyuga/HyperTMO#1]

**Comment by wuxian0** [comment]
I am a beginner in this field and have recently been looking for multi-omics data that can be used for classification. Would it be possible for you to upload or share the AD dataset? The Breast dataset has been very helpful to me, and I truly appreciate your sharing.

**Comment by ippousyuga** [comment]
Sorry, we have not uploaded the ROSMAP database to the repository cause it is necessary to apply for the web permission to use the database, maybe you can apply for it on the ROSMAP official website.
If you have any further questions, please feel free to leave a comment or contact me by e-mail!
