### ISSUE TITLE
数据集求助

### ISSUE THREAD

**Issue by Julius666** [ippousyuga/HyperTMO#2]
您好，作者，请问数据集是否进行了一些处理，可以提供一下实验用到的ROSMAP数据集么，感谢作者的回复，祝您年年中顶刊

**Comment by ippousyuga** [comment]
您好，毕业后学校邮箱被收回了，根据ROSMAP规定原始数据无法共享，否则会追究责任，您可以在ROSMAP填写进行数据申请，适用于本模型的处理后的部分数据可以联系我的个人邮箱zuoyounj@163.com
同时@wuxian0
